// Output that reaches dist/ outside the build's own chunks: legacy polyfills (a nested generate-only build),
// a service worker generated by workbox-build (Rollup's CommonJS build, written with fs after the build) and a file
// copied from node_modules by vite-plugin-static-copy.
// PWA_INJECT=1: vite-plugin-pwa's injectManifest strategy instead: it builds src/sw.js (workbox-precaching, -routing,
// -strategies) with a nested Vite build into dist/sw.js
import legacy from '@vitejs/plugin-legacy';
import { VitePWA } from 'vite-plugin-pwa';
import { viteStaticCopy } from 'vite-plugin-static-copy';

const globPatterns = ['**/*.{js,css,html}'];
export default {
  plugins: [
    legacy({ targets: ['defaults'] }),
    VitePWA(process.env.PWA_INJECT
      ? { strategies: 'injectManifest', srcDir: 'src', filename: 'sw.js', injectManifest: { globPatterns } }
      : { registerType: 'autoUpdate', workbox: { globPatterns } }),
    viteStaticCopy({ targets: [{ src: 'node_modules/normalize.css/normalize.css', dest: 'vendor' }] }),
  ],
  build: { outDir: 'dist' },
};
