// Output that reaches dist/ outside the build's own chunks: legacy polyfills (a nested generate-only build),
// a service worker generated by workbox-build (Rollup's CommonJS build, written with fs after the build) and a file
// copied from node_modules by vite-plugin-static-copy.
import legacy from '@vitejs/plugin-legacy';
import { VitePWA } from 'vite-plugin-pwa';
import { viteStaticCopy } from 'vite-plugin-static-copy';

export default {
  plugins: [
    legacy({ targets: ['defaults'] }),
    VitePWA({ registerType: 'autoUpdate', workbox: { globPatterns: ['**/*.{js,css,html}'] } }),
    viteStaticCopy({ targets: [{ src: 'node_modules/normalize.css/normalize.css', dest: 'vendor' }] }),
  ],
  build: { outDir: 'dist' },
};
